name: Trigger build workflow

on: [workflow_dispatch]

jobs:
  worker:
    name: Build docker image
    runs-on: ubuntu-latest
    steps:
      - name: Fetch current build repo
        uses: actions/checkout@v4  
        with:
          ref: main
          path: ''
          show-progress: false
          repository: ${{ secrets.REPOSITORY_PATH }}
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Setup .env
        run: printf "${{secrets.DOT_ENV}}" > ./worker/.env

      - name: Setup docker image for dynamic build workers
        run: docker compose up --build worker
