name: Trigger build workflow

on: [workflow_dispatch]

jobs:
  worker:
    name: Build docker image
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: pwd
  
      - name: x
        run: ls -ali /home/runner/work/dockerhub-builder/
    
      - name: Fetch current build repo
        uses: actions/checkout@v4  
        with:
          ref: main
          path: ''
          show-progress: false
          repository: ${{ secrets.REPOSITORY_PATH }}
          token: ${{ secrets.ACCESS_TOKEN }}

      # - name: Setup .env
      #   run: printf "${{secrets.WORKER_ENV}}" > ./worker/.env

      - name: Setup docker image
        run: ls -ali ##docker compose up --build worker
